language: php

sudo: false

php:
  - 5.6
  - 7

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - composer install

before_script:
  - cp config/autoload/travis.php.local.dist config/autoload/travis.local.php
  - mysql -uroot -e 'create database modules_test;'
  - php public/index.php migrations:migrate --no-interaction --verbose

script:
  - vendor/bin/php-cs-fixer fix --config-file=./.php_cs.dist --dry-run --diff -v
  - vendor/bin/phpunit --configuration phpunit.xml

notifications:
  irc: "irc.freenode.org#zftalk.modules"
